apiVersion: apps/v1
kind: Deployment
metadata:
  name: montage2
  labels:
    app: montage2
spec:
  selector:
    matchLabels:
      app: montage2
  replicas: 1
  template:
    metadata:
      labels:
        app: montage2
    spec:
      containers:
      - name: montage2
        image: jconallen/montage2
        imagePullPolicy: Always
        ports:
        - containerPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: montage2
  labels:
    app: montage2
spec:
  type: NodePort
  ports:
    - port: 9443
      targetPort: 9443
  selector:
    app: montage2
